// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgbqxkyqtkzbqqqazygf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnYnF4a3lxdGt6YnFxcWF6eWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMDYzNTIsImV4cCI6MjA2Mjg4MjM1Mn0.O7xOyk8bWlgQ85rVV402ZA_SVT8lUhyOSHOBFYcZbk0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);